# Matrix Operations - Part 1

In [1]:
import numpy as np

Creating a Matrix using numpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [ ]:
random_matrix = np.random.rand(3,3) # defaulr range 0 to 1 ( below 1)
print(random_matrix)

[[0.75422351 0.05457928 0.40522027]
 [0.31156082 0.18207358 0.15036347]
 [0.95586048 0.71376582 0.7947962 ]]


In [8]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size=(4,5)) # range below 100 from 0
print(random_integer_matrix)

[[24 96 98 85 22]
 [19 87 53 52 60]
 [71 66 21 19 32]
 [80 32 50 15  0]]


Matrix with all the values as 1

In [9]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [12]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [13]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [16]:
identity_matrix = np.eye(3,3) # eye = Identity
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [19]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[79 86 28 82  5]
 [11 99 43 31 16]
 [80 55 96 76  7]
 [52 38 30 26 94]]


In [20]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[79 11 80 52]
 [86 99 55 38]
 [28 43 96 30]
 [82 31 76 26]
 [ 5 16  7 94]]
